#   1  Algorithme de parcours d’une matrice

#####  Nous allons commencer à programmer des fonctions matricielles avec sagemath. Il s’agit de fonctions de la forme :
#####  f: Mn,p(R) -> Mn′,p′(R)
#####     A -> B
####  En résumé :
####  — f est le nom de la fonction ;
####  — elle prend en entrée une matrice A ∈ Mn,p (R) ;
####  — elle renvoie en sortie une matrice B ∈ Mn′ ,p′ (R) (si elle existe).

## Exemple 1. La fonction ci-contre diagonale(A) prend en entrée une matrice A de taille p×n quelconque, et renvoie
## une matrice D de meme taille telle que :
## dij = (aij si i = j) ou (0 si i != j)

In [2]:
def diagonale(A) :
    n = A.nrows()
    p = A.ncols()
    M = []
    for i in range(n) :
        for j in range(p) :
            if i == j :
                M.append(A[i, j])
    return diagonal_matrix(M)
A = matrix([[2, -1, -1, -2], [4, 4, 2, 0], [0, 4, -2, 0], [-1, -1, 0, -3]])
A, diagonale(A)

(
[ 2 -1 -1 -2]  [ 2  0  0  0]
[ 4  4  2  0]  [ 0  4  0  0]
[ 0  4 -2  0]  [ 0  0 -2  0]
[-1 -1  0 -3], [ 0  0  0 -3]
)

## Exercice 1. Écrire une fonction minimum qui trouve la valeur minimale des coefficients d’une matrice A et sa position
## (i_min,j_min) dans la matrice A.

In [18]:
def minimum(A) :
    n = A.nrows()
    p = A.ncols()
    min = A[0,0]
    istValeurMinPlusPosition = []
    for i in range(n) :
        for j in range(p) :
            if A[i,j] < min :
                min = A[i,j]
                listValeurMinPlusPosition = [min, i, j]
    return listValeurMinPlusPosition
A = matrix([[2, -1, -1, -2], [4, 4, 2, 0], [0, 4, -2, 0], [-1, -1, 0, -3]])
print("la valeur minimale est ", minimum(A)[0], "et sa position est (", minimum(A)[1], ",", minimum(A)[2], ")")

la valeur minimale est  -3 et sa position est ( 3 , 3 )


#   2 Opération élémentaire sur les lignes et les colonnes

##  Dans certains cas, on peut travailler directement sur toute une ligne ou toute une colonne d’une matrice.
##  Si M est une matrice
##  — la commande M[i, :] correspond à la ligne numéro i de la matrice ;
##  — la commande M[:, j] correspond à la colonne numéro j de la matrice.

In [9]:
M = matrix(2, 3, [1,2,3,4,5,6])
print(M)
print("---")
print(M[0, :])
print("---")
print(M[:, 1])

[1 2 3]
[4 5 6]
---
[1 2 3]
---
[2]
[5]


### Remarque importante
### Si on pose A = matrix([[1,2],[3,4]]) , puis B = A , puis que l’on modife la matrice A par A[0,0] = 7 . Que se
### passe-t-il ?

In [10]:
A=matrix([[1,2],[3,4]])
B = A
A[0, 0] = 7
A, B

(
[7 2]  [7 2]
[3 4], [3 4]
)

### La matrice B est aussi modifée !

#### Explications
#### — A ne contient pas les coefficients de la matrice, mais l’adresse où sont stockés ces coefficients (c’est plus léger
#### de manipuler l’adresse d’une matrice que toute la matrice).
#### — Comme A et B pointent vers la meme zone qui a été modifée, les deux matrices A et B sont modifées.
#### — Pour pouvoir défnir une copie de A , avec une nouvelle adresse mais les memes coefficients, on écrit 
##  B = copy(A) 
#### Les modifcations sur A ne changeront plus B.

##  Exercice 2. La méthode du pivot de Gauss repose sur trois opérations élémentaires les lignes :
##  — opération 1 : Li <- cLi avec c != 0 : on multiplie une ligne par un réel ;
##  — opération 2 : Li <- Li + cLj : on ajoute à la ligne Li un multiple d’une autre ligne Lj ;
##  — opération 3 : Li <-> Lj : on échange deux lignes.

### Écrire les fonctions op1(A, i, c) , op2(A, i, j, c) et op3(A, i, j) correspondant à ces trois opérations élémentaires.
### Attention !! la matrice A ne devra pas etre modifée pendant l’exécution de cette fonction ! Pour cela, il faudra écrire
### AA = copy(A) ou AA = A.copy() et travailler sur cette copie.

In [26]:
A=matrix([[1,2],[3,4],[5,6],[7,8]])

print(A)
print("---")

def op1(A, i, c):
    if(c==0):
        print("Erreur: le coefficient c ne doit pas être zéro.")
        return A
    AA = copy(A)
    n = A.ncols()
    for j in range(n):
        AA[i, j] = A[i, j] * c
    return AA

print(op1(A, 2, 3))
print("---")

def op2(A, i, j, c):
    if(c==0):
        print("Erreur: le coefficient c ne doit pas être zéro.")
        return A
    AA = copy(A)
    n = A.ncols()
    for k in range(n):
        AA[i, k] = A[i, k] + c * A[j, k]
    return AA

print(op2(A, 2, 1, 2))
print("---")

def op3(A, i, j):
    AA = copy(A)
    n = A.ncols()
    for k in range(n):
        temp = AA[i, k]
        AA[i, k] = AA[j, k]
        AA[j, k] = temp
    return AA

print(op3(A, 0, 2))
print("---")

[1 2]
[3 4]
[5 6]
[7 8]
---
[ 1  2]
[ 3  4]
[15 18]
[ 7  8]
---
[ 1  2]
[ 3  4]
[11 14]
[ 7  8]
---
[5 6]
[3 4]
[1 2]
[7 8]
---


#   3 Algorithme du pivot du Gauss